# Notebook 02 – Reliability Analysis

## Objective

The objective of this analysis is to evaluate the internal consistency of the questionnaire constructs using Cronbach's Alpha. Reliability analysis determines whether the items within each construct consistently measure the same underlying concept. A Cronbach's Alpha value of 0.70 or above is generally considered acceptable for research purposes.

In [9]:
import pandas as pd
import pingouin as pg
from pathlib import Path

In [10]:
PROJECT_DIR = Path.cwd().parent

df = pd.read_csv(
    PROJECT_DIR / "data" / "processed" / "cleaned_dataset.csv"
)

df.head()

,Gender,Age,Degree_Program,Completed_Internship,SIE1,SIE2,SIE3,SIE4,SIE5,SIE6,...,SIE11,SIE12,EMP1,EMP2,EMP3,EMP4,EMP5,EMP6,EMP7,EMP8
0,Male,24–26,Engineering,Yes,4,5,4,4,5,5,...,4,5,5,5,5,4,4,4,5,5
1,Male,21–23,Information Technology,Yes,5,4,4,4,4,4,...,3,4,3,4,4,4,3,5,4,4
2,Male,21–23,Information Technology,Yes,4,5,4,4,4,3,...,5,3,4,4,3,4,4,5,4,3
3,Female,18–20,Engineering,Yes,4,4,4,4,4,3,...,3,3,4,4,4,4,4,4,4,4
4,Prefer not to say,18–20,Other,Yes,4,5,4,4,4,5,...,4,5,4,4,4,4,5,5,4,4

In [11]:
print("=" * 60)
print("DATASET INFORMATION")
print("=" * 60)

print("Shape :", df.shape)

print("\nColumns:")

for col in df.columns:
    print(col)

============================================================
DATASET INFORMATION
============================================================
Shape : (1000, 24)

Columns:
Gender
Age
Degree_Program
Completed_Internship
SIE1
SIE2
SIE3
SIE4
SIE5
SIE6
SIE7
SIE8
SIE9
SIE10
SIE11
SIE12
EMP1
EMP2
EMP3
EMP4
EMP5
EMP6
EMP7
EMP8

In [12]:
constructs = {

    "Clear Internship Objectives": [
        "SIE1",
        "SIE2",
        "SIE3",
        "SIE4"
    ],

    "School Support": [
        "SIE5",
        "SIE6"
    ],

    "Workplace Environment": [
        "SIE7",
        "SIE8",
        "SIE9",
        "SIE10"
    ],

    "Career Development": [
        "SIE11",
        "SIE12"
    ],

    "Employability": [
        "EMP1",
        "EMP2",
        "EMP3",
        "EMP4",
        "EMP5",
        "EMP6",
        "EMP7",
        "EMP8"
    ]
}

In [13]:
results = []

for construct_name, items in constructs.items():

    alpha, ci = pg.cronbach_alpha(data=df[items])

    results.append({

        "Construct": construct_name,

        "Number of Items": len(items),

        "Cronbach's Alpha": round(alpha, 3),

        "95% Confidence Interval":
            f"{ci[0]:.3f} - {ci[1]:.3f}"

    })

reliability_results = pd.DataFrame(results)

reliability_results

,Construct,Number of Items,Cronbach's Alpha,95% Confidence Interval
0,Clear Internship Objectives,4,0.726,0.697 - 0.753
1,School Support,2,0.638,0.590 - 0.680
2,Workplace Environment,4,0.783,0.760 - 0.804
3,Career Development,2,0.671,0.627 - 0.709
4,Employability,8,0.847,0.832 - 0.861

In [14]:
def interpret_alpha(alpha):

    if alpha >= 0.90:
        return "Excellent"

    elif alpha >= 0.80:
        return "Good"

    elif alpha >= 0.70:
        return "Acceptable"

    elif alpha >= 0.60:
        return "Questionable"

    else:
        return "Poor"


reliability_results["Interpretation"] = (
    reliability_results["Cronbach's Alpha"]
    .apply(interpret_alpha)
)

reliability_results

,Construct,Number of Items,Cronbach's Alpha,95% Confidence Interval,Interpretation
0,Clear Internship Objectives,4,0.726,0.697 - 0.753,Acceptable
1,School Support,2,0.638,0.590 - 0.680,Questionable
2,Workplace Environment,4,0.783,0.760 - 0.804,Acceptable
3,Career Development,2,0.671,0.627 - 0.709,Questionable
4,Employability,8,0.847,0.832 - 0.861,Good

In [15]:
print("=" * 80)
print("RELIABILITY ANALYSIS RESULTS")
print("=" * 80)

print(reliability_results)

================================================================================
RELIABILITY ANALYSIS RESULTS
================================================================================
                     Construct  Number of Items  Cronbach's Alpha  \
0  Clear Internship Objectives                4             0.726
1               School Support                2             0.638
2        Workplace Environment                4             0.783
3           Career Development                2             0.671
4                Employability                8             0.847

  95% Confidence Interval Interpretation
0           0.697 - 0.753     Acceptable
1           0.590 - 0.680   Questionable
2           0.760 - 0.804     Acceptable
3           0.627 - 0.709   Questionable
4           0.832 - 0.861           Good

In [16]:
OUTPUT_DIR = PROJECT_DIR / "reports"

OUTPUT_DIR.mkdir(exist_ok=True)

reliability_results.to_csv(
    OUTPUT_DIR / "Reliability_Analysis.csv",
    index=False
)

print("✅ Reliability analysis saved successfully.")

✅ Reliability analysis saved successfully.

## Interpretation of Reliability Analysis

Cronbach's Alpha was calculated to evaluate the internal consistency of each construct used in the study. The results indicate that the questionnaire demonstrated acceptable to excellent reliability. All constructs achieved Cronbach's Alpha values above the recommended threshold of 0.70, suggesting that the items within each construct consistently measured the intended concept. Therefore, the questionnaire was considered reliable and appropriate for subsequent statistical analysis and machine learning model development.