# 06 Feature Engineering

## Objective

The objective of this notebook is to prepare the dataset for machine learning model development. Feature engineering transforms the processed questionnaire responses into meaningful predictive features based on the conceptual framework. This step includes selecting relevant variables, constructing the final machine learning dataset, checking feature distributions, preparing multiple feature sets, splitting the data into training and testing subsets, and scaling features where appropriate.

In [1]:
import pandas as pd
import numpy as np

from pathlib import Path

from sklearn.model_selection import train_test_split

from sklearn.preprocessing import StandardScaler

In [2]:
PROJECT_DIR = Path.cwd().parent

df = pd.read_csv(
    PROJECT_DIR /
    "data" /
    "processed" /
    "descriptive_dataset.csv"
)

df.head()

,Gender,Age,Degree_Program,Completed_Internship,SIE1,SIE2,SIE3,SIE4,SIE5,SIE6,...,EMP4,EMP5,EMP6,EMP7,EMP8,Clear_Objectives,School_Support,Workplace_Environment,Career_Development,Employability_Score
0,Male,24–26,Engineering,Yes,4,5,4,4,5,5,...,4,4,4,5,5,4.25,5.0,4.25,4.5,4.625
1,Male,21–23,Information Technology,Yes,5,4,4,4,4,4,...,4,3,5,4,4,4.25,4.0,3.75,3.5,3.875
2,Male,21–23,Information Technology,Yes,4,5,4,4,4,3,...,4,4,5,4,3,4.25,3.5,4.00,4.0,3.875
3,Female,18–20,Engineering,Yes,4,4,4,4,4,3,...,4,4,4,4,4,4.00,3.5,3.75,3.0,4.000
4,Prefer not to say,18–20,Other,Yes,4,5,4,4,4,5,...,4,5,5,4,4,4.25,4.5,4.25,4.5,4.250

In [3]:
print(df.shape)

print(df.columns.tolist())

(1000, 29)
['Gender', 'Age', 'Degree_Program', 'Completed_Internship', 'SIE1', 'SIE2', 'SIE3', 'SIE4', 'SIE5', 'SIE6', 'SIE7', 'SIE8', 'SIE9', 'SIE10', 'SIE11', 'SIE12', 'EMP1', 'EMP2', 'EMP3', 'EMP4', 'EMP5', 'EMP6', 'EMP7', 'EMP8', 'Clear_Objectives', 'School_Support', 'Workplace_Environment', 'Career_Development', 'Employability_Score']

In [4]:
features_A = [

    "Clear_Objectives",

    "School_Support",

    "Workplace_Environment",

    "Career_Development"

]

target = "Employability_Score"

X_A = df[features_A]

y = df[target]

In [5]:
features_B = [

    "Gender",

    "Age",

    "Degree_Program",

    "Clear_Objectives",

    "School_Support",

    "Workplace_Environment",

    "Career_Development"

]

In [6]:
X_B = df[features_B].copy()

X_B = pd.get_dummies(

    X_B,

    columns=[

        "Gender",

        "Age",

        "Degree_Program"

    ],

    drop_first=True

)

In [7]:
print(X_A.head())

print(X_B.head())

   Clear_Objectives  School_Support  Workplace_Environment  Career_Development
0              4.25             5.0                   4.25                 4.5
1              4.25             4.0                   3.75                 3.5
2              4.25             3.5                   4.00                 4.0
3              4.00             3.5                   3.75                 3.0
4              4.25             4.5                   4.25                 4.5
   Clear_Objectives  School_Support  Workplace_Environment  \
0              4.25             5.0                   4.25
1              4.25             4.0                   3.75
2              4.25             3.5                   4.00
3              4.00             3.5                   3.75
4              4.25             4.5                   4.25

   Career_Development  Gender_Male  Gender_Prefer not to say  Age_21–23  \
0                 4.5         True                     False      False
1                 3.5         True                     False       True
2                 4.0         True                     False       True
3                 3.0        False                     False      False
4                 4.5        False                      True      False

   Age_24–26  Age_Above 26  Degree_Program_Engineering  \
0       True         False                        True
1      False         False                       False
2      False         False                       False
3      False         False                        True
4      False         False                       False

   Degree_Program_Information Technology  Degree_Program_Other
0                                  False                 False
1                                   True                 False
2                                   True                 False
3                                  False                 False
4                                  False                  True

In [8]:
print(X_A.isnull().sum())

print(X_B.isnull().sum())

Clear_Objectives         0
School_Support           0
Workplace_Environment    0
Career_Development       0
dtype: int64
Clear_Objectives                         0
School_Support                           0
Workplace_Environment                    0
Career_Development                       0
Gender_Male                              0
Gender_Prefer not to say                 0
Age_21–23                                0
Age_24–26                                0
Age_Above 26                             0
Degree_Program_Engineering               0
Degree_Program_Information Technology    0
Degree_Program_Other                     0
dtype: int64

In [9]:
X_A.describe()

,Clear_Objectives,School_Support,Workplace_Environment,Career_Development
count,1000.000000,1000.000000,1000.000000,1000.00000
mean,4.040750,4.167500,4.144250,3.96350
std,0.358511,0.496931,0.438973,0.45456
min,1.250000,1.000000,1.000000,1.00000
25%,4.000000,4.000000,4.000000,4.00000
50%,4.000000,4.000000,4.000000,4.00000
75%,4.250000,4.500000,4.250000,4.00000
max,5.000000,5.000000,5.000000,5.00000

In [10]:
X_B.describe()

,Clear_Objectives,School_Support,Workplace_Environment,Career_Development
count,1000.000000,1000.000000,1000.000000,1000.00000
mean,4.040750,4.167500,4.144250,3.96350
std,0.358511,0.496931,0.438973,0.45456
min,1.250000,1.000000,1.000000,1.00000
25%,4.000000,4.000000,4.000000,4.00000
50%,4.000000,4.000000,4.000000,4.00000
75%,4.250000,4.500000,4.250000,4.00000
max,5.000000,5.000000,5.000000,5.00000

In [11]:
X_train_A, X_test_A, y_train, y_test = train_test_split(

    X_A,

    y,

    test_size=0.20,

    random_state=42

)

In [12]:
X_train_B, X_test_B, y_train_B, y_test_B = train_test_split(

    X_B,

    y,

    test_size=0.20,

    random_state=42

)

In [13]:
scaler_A = StandardScaler()

X_train_A_scaled = scaler_A.fit_transform(
    X_train_A
)

X_test_A_scaled = scaler_A.transform(
    X_test_A
)

In [14]:
scaler_B = StandardScaler()

X_train_B_scaled = scaler_B.fit_transform(
    X_train_B
)

X_test_B_scaled = scaler_B.transform(
    X_test_B
)

In [15]:
print(X_train_A.shape)

print(X_test_A.shape)

print(y_train.shape)

print(y_test.shape)

(800, 4)
(200, 4)
(800,)
(200,)

In [16]:
OUTPUT_DIR = PROJECT_DIR / "data" / "ml"

OUTPUT_DIR.mkdir(exist_ok=True)

X_train_A.to_csv(
    OUTPUT_DIR / "X_train_A.csv",
    index=False
)

X_test_A.to_csv(
    OUTPUT_DIR / "X_test_A.csv",
    index=False
)

X_train_B.to_csv(
    OUTPUT_DIR / "X_train_B.csv",
    index=False
)

X_test_B.to_csv(
    OUTPUT_DIR / "X_test_B.csv",
    index=False
)

y_train.to_csv(
    OUTPUT_DIR / "y_train.csv",
    index=False
)

y_test.to_csv(
    OUTPUT_DIR / "y_test.csv",
    index=False
)

## Feature Engineering

Feature engineering was performed to prepare the dataset for machine learning. Two feature sets were developed.

Model A consisted of the Internship Experience constructs derived from the conceptual framework.

Model B extended Model A by including demographic variables to evaluate whether participant characteristics improved predictive performance.

Categorical variables were encoded using one-hot encoding. The dataset was divided into training (80%) and testing (20%) subsets using a fixed random state to ensure reproducibility. Feature scaling using StandardScaler was applied where appropriate for regression-based models.

In [17]:
print("Model A")
print(X_A.head())
print(X_A.shape)

print()

print("Model B")
print(X_B.head())
print(X_B.shape)

Model A
   Clear_Objectives  School_Support  Workplace_Environment  Career_Development
0              4.25             5.0                   4.25                 4.5
1              4.25             4.0                   3.75                 3.5
2              4.25             3.5                   4.00                 4.0
3              4.00             3.5                   3.75                 3.0
4              4.25             4.5                   4.25                 4.5
(1000, 4)

Model B
   Clear_Objectives  School_Support  Workplace_Environment  \
0              4.25             5.0                   4.25
1              4.25             4.0                   3.75
2              4.25             3.5                   4.00
3              4.00             3.5                   3.75
4              4.25             4.5                   4.25

   Career_Development  Gender_Male  Gender_Prefer not to say  Age_21–23  \
0                 4.5         True                     False      False
1                 3.5         True                     False       True
2                 4.0         True                     False       True
3                 3.0        False                     False      False
4                 4.5        False                      True      False

   Age_24–26  Age_Above 26  Degree_Program_Engineering  \
0       True         False                        True
1      False         False                       False
2      False         False                       False
3      False         False                        True
4      False         False                       False

   Degree_Program_Information Technology  Degree_Program_Other
0                                  False                 False
1                                   True                 False
2                                   True                 False
3                                  False                 False
4                                  False                  True
(1000, 12)

In [18]:
print("Model A")
print(X_train_A.shape)
print(X_test_A.shape)
print(y_train.shape)
print(y_test.shape)

print()

print("Model B")
print(X_train_B.shape)
print(X_test_B.shape)

Model A
(800, 4)
(200, 4)
(800,)
(200,)

Model B
(800, 12)
(200, 12)

In [19]:
print(X_train_A.isnull().sum())

print()

print(X_train_B.isnull().sum())

print()

print(y_train.isnull().sum())

Clear_Objectives         0
School_Support           0
Workplace_Environment    0
Career_Development       0
dtype: int64

Clear_Objectives                         0
School_Support                           0
Workplace_Environment                    0
Career_Development                       0
Gender_Male                              0
Gender_Prefer not to say                 0
Age_21–23                                0
Age_24–26                                0
Age_Above 26                             0
Degree_Program_Engineering               0
Degree_Program_Information Technology    0
Degree_Program_Other                     0
dtype: int64

0

In [20]:
print(type(X_train_A_scaled))
print(X_train_A_scaled.shape)

print(type(X_train_B_scaled))
print(X_train_B_scaled.shape)

<class 'numpy.ndarray'>
(800, 4)
<class 'numpy.ndarray'>
(800, 12)