# Phase 03 — Psychological Capital → Employability

## Step 01 — Data Preprocessing

This notebook prepares the Phase 03 dataset for statistical analysis and machine learning.

The preprocessing stage includes:

- Loading the raw Phase 03 dataset
- Validating required columns
- Checking missing values and duplicate responses
- Validating 5-point Likert-scale responses
- Creating Psychological Capital construct scores
- Creating Employability construct scores
- Creating overall PsyCap and Employability averages
- Inspecting demographic variables
- Saving the cleaned and prepared dataset for later analysis

No predictive model is trained in this step.

In [42]:
from pathlib import Path

import numpy as np
import pandas as pd

In [43]:
from pathlib import Path

PROJECT_DIR = Path.cwd()

if PROJECT_DIR.name == "phase3_psycap":
    PROJECT_DIR = PROJECT_DIR.parent.parent

CANDIDATE_RAW_FILES = [
    PROJECT_DIR / "data" / "raw" / "phase03_psycap_new.csv",
    PROJECT_DIR / "data" / "raw" / "phase3_psycap_raw.csv",
]

RAW_DATA_PATH = next(
    (path for path in CANDIDATE_RAW_FILES if path.exists()),
    CANDIDATE_RAW_FILES[0],
)

PROCESSED_DIR = (
    PROJECT_DIR
    / "data"
    / "processed"
)

REPORT_DIR = (
    PROJECT_DIR
    / "reports"
    / "phase3"
    / "preprocessing"
)

PROCESSED_DIR.mkdir(
    parents=True,
    exist_ok=True
)

REPORT_DIR.mkdir(
    parents=True,
    exist_ok=True
)

print("PROJECT_DIR:", PROJECT_DIR)
print("RAW_DATA_PATH:", RAW_DATA_PATH)
print("PROCESSED_DIR:", PROCESSED_DIR)
print("REPORT_DIR:", REPORT_DIR)

PROJECT_DIR: d:\internship-employability-project
RAW_DATA_PATH: d:\internship-employability-project\data\raw\phase3_psycap_raw.csv
PROCESSED_DIR: d:\internship-employability-project\data\processed
REPORT_DIR: d:\internship-employability-project\reports\phase3\preprocessing

In [44]:
df = pd.read_csv(
    RAW_DATA_PATH
)

print(
    "Dataset shape:",
    df.shape
)

df.head()

Dataset shape: (1000, 30)

,Response ID,Gender,Age,Degree Program,Internship Status,I can find various ways to overcome obstacles that arise during my studies.,I realize that different approaches can be used to overcome the problems I face in my studies.,I am committed to doing my best and working hard to achieve the goals I set.,I have high hopes that I can succeed in my learning activities.,I am optimistic that the time and effort I invest now will bring positive results in the future.,...,I have a satisfactory level of professional experience to operate on the job,I am able to convince others about work when decisions within the team have to be made,Building social relationships can have a positive effect on my life,I have a clear plan for my career,I have clear career goals,I have a clear strategy to achieve my career goals,I have a clear idea of the target industry according to my field of work,I am able to achieve a balance between my work goals and the support of my colleagues,I am able to achieve a balance between my career goals and the support of my colleagues,Data Source
0,1,Female,18–20,Information Technology,Yes,5,4,4,4,5,...,4,4,4,5,5,5,5,5,5,real
1,2,Female,21–23,Business Management,Yes,3,5,5,4,4,...,4,3,5,4,4,2,4,3,2,real
2,3,Male,18–20,Information Technology,Yes,4,5,4,5,4,...,4,4,5,4,3,3,4,3,4,real
3,4,Male,18–20,Engineering,Yes,4,4,4,4,4,...,4,4,4,4,4,4,4,4,4,real
4,5,Male,21–23,Business Management,Yes,3,3,5,3,5,...,4,5,5,4,4,5,5,4,4,real

Inspect All Columns

In [45]:
print(
    "Number of columns:",
    len(df.columns)
)

print(
    "\nColumn names:"
)

for column in df.columns:
    print(column)

Number of columns: 30

Column names:
Response ID
Gender
Age
Degree Program
Internship Status
I can find various ways to overcome obstacles that arise during my studies.
I realize that different approaches can be used to overcome the problems I face in my studies.
I am committed to doing my best and working hard to achieve the goals I set.
I have high hopes that I can succeed in my learning activities.
I am optimistic that the time and effort I invest now will bring positive results in the future.
I tend to identify positive lessons from my learning experiences, whether they involve success or failure.
I can identify and analyze problems that arise during my learning activities.
When I receive low grades, I try to identify the reasons and find ways to improve.
I understand that failure can happen, and I am able to recover and continue working toward long-term success.
I believe that I can successfully complete difficult tasks.
I am confident enough to ask my teacher or lecturer for help when I have difficulty completing an assignment.
I am confident that I can make a meaningful and useful contribution to others using my abilities.
I have the ability to discuss professionally with various professionals or technical aspects of work
I achieved a level of education sufficient to operate as a prospective new employee in the job
I am able to evaluate sufficient technical skills to be able to complete tasks or solve problems at school
I have a satisfactory level of professional experience to operate on the job
I am able to convince others about work when decisions within the team have to be made
Building social relationships can have a positive effect on my life
I have a clear plan for my career
I have clear career goals
I have a clear strategy to achieve my career goals
I have a clear idea of the target industry according to my field of work
I am able to achieve a balance between my work goals and the support of my colleagues
I am able to achieve a balance between my career goals and the support of my colleagues
Data Source

In [46]:
COLUMN_RENAME_MAP = {

    # Identification
    "Response ID": "Response_ID",

    # Psychological Capital — Hope
    "I can find various ways to overcome obstacles that arise during my studies.": "PsyCap1",

    "I realize that different approaches can be used to overcome the problems I face in my studies.": "PsyCap2",

    "I am committed to doing my best and working hard to achieve the goals I set.": "PsyCap3",

    # Psychological Capital — Optimism
    "I have high hopes that I can succeed in my learning activities.": "PsyCap4",

    "I am optimistic that the time and effort I invest now will bring positive results in the future.": "PsyCap5",

    "I tend to identify positive lessons from my learning experiences, whether they involve success or failure.": "PsyCap6",

    # Psychological Capital — Resilience
    "I can identify and analyze problems that arise during my learning activities.": "PsyCap7",

    "When I receive low grades, I try to identify the reasons and find ways to improve.": "PsyCap8",

    "I understand that failure can happen, and I am able to recover and continue working toward long-term success.": "PsyCap9",

    # Psychological Capital — Self-Efficacy
    "I believe that I can successfully complete difficult tasks.": "PsyCap10",

    "I am confident enough to ask my teacher or lecturer for help when I have difficulty completing an assignment.": "PsyCap11",

    "I am confident that I can make a meaningful and useful contribution to others using my abilities.": "PsyCap12",

    # Employability
    "I have the ability to discuss professionally with various professionals or technical aspects of work": "EVS1",

    "I achieved a level of education sufficient to operate as a prospective new employee in the job": "EVS2",

    "I am able to evaluate sufficient technical skills to be able to complete tasks or solve problems at school": "EVS3",

    "I have a satisfactory level of professional experience to operate on the job": "EVS4",

    "I am able to convince others about work when decisions within the team have to be made": "EVS5",

    "Building social relationships can have a positive effect on my life": "EVS6",

    "I have a clear plan for my career": "EVS7",

    "I have clear career goals": "EVS8",

    "I have a clear strategy to achieve my career goals": "EVS9",

    "I have a clear idea of the target industry according to my field of work": "EVS10",

    "I am able to achieve a balance between my work goals and the support of my colleagues": "EVS11",

    "I am able to achieve a balance between my career goals and the support of my colleagues": "EVS12",

    # Data source
    "Data Source": "data_source"
}

In [47]:
df = df.rename(
    columns=COLUMN_RENAME_MAP
)

print(
    "Columns renamed successfully."
)

print(
    "Number of columns:",
    len(df.columns)
)

for column in df.columns:
    print(column)

Columns renamed successfully.
Number of columns: 30
Response_ID
Gender
Age
Degree Program
Internship Status
PsyCap1
PsyCap2
PsyCap3
PsyCap4
PsyCap5
PsyCap6
PsyCap7
PsyCap8
PsyCap9
PsyCap10
PsyCap11
PsyCap12
EVS1
EVS2
EVS3
EVS4
EVS5
EVS6
EVS7
EVS8
EVS9
EVS10
EVS11
EVS12
data_source

Define Column Groups

In [48]:
PSYCAP_ITEMS = [
    "PsyCap1",
    "PsyCap2",
    "PsyCap3",
    "PsyCap4",
    "PsyCap5",
    "PsyCap6",
    "PsyCap7",
    "PsyCap8",
    "PsyCap9",
    "PsyCap10",
    "PsyCap11",
    "PsyCap12"
]

EVS_ITEMS = [
    "EVS1",
    "EVS2",
    "EVS3",
    "EVS4",
    "EVS5",
    "EVS6",
    "EVS7",
    "EVS8",
    "EVS9",
    "EVS10",
    "EVS11",
    "EVS12"
]

DEMOGRAPHIC_COLUMNS = [
    "Gender",
    "Age",
    "Degree Program",
    "Internship Status"
]

Define PsyCap Construct Mapping

In [49]:
PSYCAP_CONSTRUCTS = {

    "Hope_avg": [
        "PsyCap1",
        "PsyCap2",
        "PsyCap3"
    ],

    "Optimism_avg": [
        "PsyCap4",
        "PsyCap5",
        "PsyCap6"
    ],

    "Resilience_avg": [
        "PsyCap7",
        "PsyCap8",
        "PsyCap9"
    ],

    "SelfEfficacy_avg": [
        "PsyCap10",
        "PsyCap11",
        "PsyCap12"
    ]
}

Define EVS Construct Mapping

In [50]:
EVS_CONSTRUCTS = {

    "HumanCapital_avg": [
        "EVS1",
        "EVS2",
        "EVS3"
    ],

    "SocialCapital_avg": [
        "EVS4",
        "EVS5"
    ],

    "CareerIdentity_avg": [
        "EVS6",
        "EVS7",
        "EVS8",
        "EVS9"
    ],

    "EnvironmentalMonitoring_avg": [
        "EVS10"
    ],

    "Balance_avg": [
        "EVS11",
        "EVS12"
    ]
}

Validate Required Columns

In [51]:
required_columns = (
    ["Response_ID"]
    + DEMOGRAPHIC_COLUMNS
    + PSYCAP_ITEMS
    + EVS_ITEMS
)

missing_columns = [
    column
    for column in required_columns
    if column not in df.columns
]

if missing_columns:
    raise ValueError(
        f"Missing required columns: {missing_columns}"
    )

print(
    "Required column validation passed."
)

Required column validation passed.

Check Duplicate Response IDs

In [52]:
duplicate_response_ids = (
    df["Response_ID"]
    .duplicated()
    .sum()
)

print(
    "Duplicate Response_ID count:",
    duplicate_response_ids
)

Duplicate Response_ID count: 0

In [53]:
duplicate_rows = df[
    df["Response_ID"].duplicated(
        keep=False
    )
]

duplicate_rows

Empty DataFrame
Columns: [Response_ID, Gender, Age, Degree Program, Internship Status, PsyCap1, PsyCap2, PsyCap3, PsyCap4, PsyCap5, PsyCap6, PsyCap7, PsyCap8, PsyCap9, PsyCap10, PsyCap11, PsyCap12, EVS1, EVS2, EVS3, EVS4, EVS5, EVS6, EVS7, EVS8, EVS9, EVS10, EVS11, EVS12, data_source]
Index: []

[0 rows x 30 columns]

Check Exact Duplicate Rows

In [54]:
exact_duplicate_rows = (
    df.duplicated()
    .sum()
)

print(
    "Exact duplicate row count:",
    exact_duplicate_rows
)

Exact duplicate row count: 0

Missing Value Check

In [55]:
missing_summary = (
    df[required_columns]
    .isnull()
    .sum()
    .sort_values(
        ascending=False
    )
)

missing_summary

Response_ID          0
Gender               0
Age                  0
Degree Program       0
Internship Status    0
PsyCap1              0
PsyCap2              0
PsyCap3              0
PsyCap4              0
PsyCap5              0
PsyCap6              0
PsyCap7              0
PsyCap8              0
PsyCap9              0
PsyCap10             0
PsyCap11             0
PsyCap12             0
EVS1                 0
EVS2                 0
EVS3                 0
EVS4                 0
EVS5                 0
EVS6                 0
EVS7                 0
EVS8                 0
EVS9                 0
EVS10                0
EVS11                0
EVS12                0
dtype: int64

In [56]:
total_missing = int(
    missing_summary.sum()
)

print(
    "Total missing values:",
    total_missing
)

Total missing values: 0

Validate Numeric Item Types

In [57]:
for column in (
    PSYCAP_ITEMS
    +
    EVS_ITEMS
):

    df[column] = pd.to_numeric(
        df[column],
        errors="coerce"
    )

In [58]:
numeric_conversion_missing = (
    df[
        PSYCAP_ITEMS
        +
        EVS_ITEMS
    ]
    .isnull()
    .sum()
)

numeric_conversion_missing

PsyCap1     0
PsyCap2     0
PsyCap3     0
PsyCap4     0
PsyCap5     0
PsyCap6     0
PsyCap7     0
PsyCap8     0
PsyCap9     0
PsyCap10    0
PsyCap11    0
PsyCap12    0
EVS1        0
EVS2        0
EVS3        0
EVS4        0
EVS5        0
EVS6        0
EVS7        0
EVS8        0
EVS9        0
EVS10       0
EVS11       0
EVS12       0
dtype: int64

Validate Likert Range

In [59]:
likert_columns = (
    PSYCAP_ITEMS
    +
    EVS_ITEMS
)

invalid_likert_values = {}

for column in likert_columns:

    invalid_count = (
        ~df[column].between(
            1,
            5
        )
    ).sum()

    if invalid_count > 0:
        invalid_likert_values[
            column
        ] = int(
            invalid_count
        )

print(
    "Invalid Likert values:",
    invalid_likert_values
)

Invalid Likert values: {}

Check Item Min/Max

In [60]:
item_range_summary = pd.DataFrame({

    "Minimum": (
        df[likert_columns]
        .min()
    ),

    "Maximum": (
        df[likert_columns]
        .max()
    )
})

item_range_summary

          Minimum  Maximum
PsyCap1         1        5
PsyCap2         1        5
PsyCap3         1        5
PsyCap4         1        5
PsyCap5         1        5
PsyCap6         1        5
PsyCap7         1        5
PsyCap8         1        5
PsyCap9         1        5
PsyCap10        1        5
PsyCap11        1        5
PsyCap12        1        5
EVS1            1        5
EVS2            1        5
EVS3            1        5
EVS4            1        5
EVS5            1        5
EVS6            1        5
EVS7            1        5
EVS8            1        5
EVS9            1        5
EVS10           1        5
EVS11           1        5
EVS12           1        5

Create PsyCap Construct Scores

In [61]:
for construct_name, item_list in (
    PSYCAP_CONSTRUCTS.items()
):

    df[construct_name] = (
        df[item_list]
        .mean(
            axis=1
        )
    )

Create Overall PsyCap Score

In [62]:
df["PsyCap_avg"] = (
    df[PSYCAP_ITEMS]
    .mean(
        axis=1
    )
)

Create EVS Construct Scores

In [63]:
for construct_name, item_list in (
    EVS_CONSTRUCTS.items()
):

    df[construct_name] = (
        df[item_list]
        .mean(
            axis=1
        )
    )

Create Overall Employability Score

In [64]:
df["EVS_avg"] = (
    df[EVS_ITEMS]
    .mean(
        axis=1
    )
)

Verify Construct Calculations

In [65]:
construct_columns = [
    "Hope_avg",
    "Optimism_avg",
    "Resilience_avg",
    "SelfEfficacy_avg",
    "PsyCap_avg",

    "HumanCapital_avg",
    "SocialCapital_avg",
    "CareerIdentity_avg",
    "EnvironmentalMonitoring_avg",
    "Balance_avg",
    "EVS_avg"
]

df[
    construct_columns
].head()

,Hope_avg,Optimism_avg,Resilience_avg,SelfEfficacy_avg,PsyCap_avg,HumanCapital_avg,SocialCapital_avg,CareerIdentity_avg,EnvironmentalMonitoring_avg,Balance_avg,EVS_avg
0,4.333333,4.333333,4.000000,3.666667,4.083333,5.000000,4.0,4.75,5.0,5.0,4.750000
1,4.333333,4.000000,3.666667,3.666667,3.916667,3.666667,3.5,3.75,4.0,2.5,3.500000
2,4.333333,4.333333,3.333333,3.333333,3.833333,3.666667,4.0,3.75,4.0,3.5,3.750000
3,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.0,4.00,4.0,4.0,4.000000
4,3.666667,4.000000,3.666667,3.333333,3.666667,4.000000,4.5,4.50,5.0,4.0,4.333333

Validate Construct Ranges

In [66]:
construct_range_summary = pd.DataFrame({

    "Minimum": (
        df[
            construct_columns
        ]
        .min()
    ),

    "Maximum": (
        df[
            construct_columns
        ]
        .max()
    )
})

construct_range_summary

                              Minimum  Maximum
Hope_avg                     1.000000      5.0
Optimism_avg                 1.000000      5.0
Resilience_avg               1.333333      5.0
SelfEfficacy_avg             1.333333      5.0
PsyCap_avg                   1.333333      5.0
HumanCapital_avg             1.000000      5.0
SocialCapital_avg            1.000000      5.0
CareerIdentity_avg           1.000000      5.0
EnvironmentalMonitoring_avg  1.000000      5.0
Balance_avg                  1.000000      5.0
EVS_avg                      1.000000      5.0

Automatic Range Validation

In [67]:
invalid_constructs = {}

for column in construct_columns:

    invalid_count = (
        ~df[column].between(
            1,
            5
        )
    ).sum()

    if invalid_count > 0:

        invalid_constructs[
            column
        ] = int(
            invalid_count
        )

print(
    "Invalid construct scores:",
    invalid_constructs
)

Invalid construct scores: {}

Manually Verify One Respondent

In [68]:
sample_index = 0

sample_psycap = df.loc[
    sample_index,
    PSYCAP_ITEMS
]

manual_psycap_average = (
    sample_psycap.mean()
)

stored_psycap_average = (
    df.loc[
        sample_index,
        "PsyCap_avg"
    ]
)

print(
    "Manual PsyCap average:",
    manual_psycap_average
)

print(
    "Stored PsyCap average:",
    stored_psycap_average
)

print(
    "Difference:",
    abs(
        manual_psycap_average
        -
        stored_psycap_average
    )
)

Manual PsyCap average: 4.083333333333333
Stored PsyCap average: 4.083333333333333
Difference: 0.0

Check Individual Construct Calculation

In [69]:
sample_hope_manual = (
    df.loc[
        sample_index,
        [
            "PsyCap1",
            "PsyCap2",
            "PsyCap3"
        ]
    ]
    .mean()
)

sample_hope_stored = (
    df.loc[
        sample_index,
        "Hope_avg"
    ]
)

print(
    "Manual Hope average:",
    sample_hope_manual
)

print(
    "Stored Hope average:",
    sample_hope_stored
)

Manual Hope average: 4.333333333333333
Stored Hope average: 4.333333333333333

Inspect Demographic Variables

In [70]:
for column in DEMOGRAPHIC_COLUMNS:

    print(
        f"\n{column}"
    )

    print(
        df[column]
        .value_counts(
            dropna=False
        )
    )

Gender
Gender
Female               515
Male                 454
Prefer not to say     31
Name: count, dtype: int64

Age
Age
21–23          543
18–20          215
24–26          192
27 or above     50
Name: count, dtype: int64

Degree Program
Degree Program
Information Technology    552
Business Management       207
Engineering               143
Other                      98
Name: count, dtype: int64

Internship Status
Internship Status
Yes    676
No     324
Name: count, dtype: int64

Demographic Percentage Summary

In [71]:
demographic_summary = []

for column in DEMOGRAPHIC_COLUMNS:

    counts = (
        df[column]
        .value_counts(
            dropna=False
        )
    )

    percentages = (
        df[column]
        .value_counts(
            normalize=True,
            dropna=False
        )
        * 100
    )

    for category in counts.index:

        demographic_summary.append({
            "Variable": column,
            "Category": category,
            "Count": int(
                counts[
                    category
                ]
            ),
            "Percentage": float(
                percentages[
                    category
                ]
            )
        })

demographic_summary = pd.DataFrame(
    demographic_summary
)

demographic_summary

             Variable                Category  Count  Percentage
0              Gender                  Female    515        51.5
1              Gender                    Male    454        45.4
2              Gender       Prefer not to say     31         3.1
3                 Age                   21–23    543        54.3
4                 Age                   18–20    215        21.5
5                 Age                   24–26    192        19.2
6                 Age             27 or above     50         5.0
7      Degree Program  Information Technology    552        55.2
8      Degree Program     Business Management    207        20.7
9      Degree Program             Engineering    143        14.3
10     Degree Program                   Other     98         9.8
11  Internship Status                     Yes    676        67.6
12  Internship Status                      No    324        32.4

Check data_source Distribution

In [72]:
if "data_source" in df.columns:

    print(
        df[
            "data_source"
        ]
        .value_counts(
            dropna=False
        )
    )

data_source
synthetic    734
real         266
Name: count, dtype: int64

In [73]:
print(
    "Prepared dataset shape:",
    df.shape
)

Prepared dataset shape: (1000, 41)

Create Main Prepared Dataset

In [74]:
PREPARED_DATA_PATH = (
    PROCESSED_DIR
    / "phase3_psycap_prepared.csv"
)

df.to_csv(
    PREPARED_DATA_PATH,
    index=False
)

print(
    "Prepared dataset saved:",
    PREPARED_DATA_PATH
)

Prepared dataset saved: d:\internship-employability-project\data\processed\phase3_psycap_prepared.csv

Create Item-Level ML Dataset

Create Item-Level ML Dataset

In [75]:
item_level_columns = (
    ["Response_ID"]
    +
    PSYCAP_ITEMS
    +
    ["EVS_avg"]
)

phase3_item_ml = df[
    item_level_columns
].copy()

ITEM_ML_PATH = (
    PROCESSED_DIR
    / "phase3_psycap_item_features.csv"
)

phase3_item_ml.to_csv(
    ITEM_ML_PATH,
    index=False
)

print(
    "Item-level ML dataset saved:",
    ITEM_ML_PATH
)

Item-level ML dataset saved: d:\internship-employability-project\data\processed\phase3_psycap_item_features.csv

Create Construct-Level ML Dataset

In [76]:
construct_level_columns = [
    "Response_ID",

    "Hope_avg",
    "Optimism_avg",
    "Resilience_avg",
    "SelfEfficacy_avg",

    "EVS_avg"
]

phase3_construct_ml = df[
    construct_level_columns
].copy()

CONSTRUCT_ML_PATH = (
    PROCESSED_DIR
    / "phase3_psycap_construct_features.csv"
)

phase3_construct_ml.to_csv(
    CONSTRUCT_ML_PATH,
    index=False
)

print(
    "Construct-level ML dataset saved:",
    CONSTRUCT_ML_PATH
)

Construct-level ML dataset saved: d:\internship-employability-project\data\processed\phase3_psycap_construct_features.csv

Create Overall PsyCap ML Dataset

In [77]:
overall_psycap_ml = df[
    [
        "Response_ID",
        "PsyCap_avg",
        "EVS_avg"
    ]
].copy()

OVERALL_ML_PATH = (
    PROCESSED_DIR
    / "phase3_psycap_overall_feature.csv"
)

overall_psycap_ml.to_csv(
    OVERALL_ML_PATH,
    index=False
)

print(
    "Overall PsyCap ML dataset saved:",
    OVERALL_ML_PATH
)

Overall PsyCap ML dataset saved: d:\internship-employability-project\data\processed\phase3_psycap_overall_feature.csv

Save Demographic Summary

In [78]:
DEMOGRAPHIC_REPORT_PATH = (
    REPORT_DIR
    / "Demographic_Summary.csv"
)

demographic_summary.to_csv(
    DEMOGRAPHIC_REPORT_PATH,
    index=False
)

print(
    "Demographic summary saved:",
    DEMOGRAPHIC_REPORT_PATH
)

Demographic summary saved: d:\internship-employability-project\reports\phase3\preprocessing\Demographic_Summary.csv

Create Preprocessing Validation Summary

In [79]:
preprocessing_validation = pd.DataFrame({

    "Validation_Check": [
        "Required columns",
        "Duplicate Response_ID",
        "Exact duplicate rows",
        "Missing required values",
        "Likert value range",
        "Construct value range",
        "PsyCap calculation verification"
    ],

    "Status": [
        (
            "PASS"
            if len(
                missing_columns
            ) == 0
            else "FAIL"
        ),

        (
            "PASS"
            if duplicate_response_ids == 0
            else "REVIEW"
        ),

        (
            "PASS"
            if exact_duplicate_rows == 0
            else "REVIEW"
        ),

        (
            "PASS"
            if total_missing == 0
            else "REVIEW"
        ),

        (
            "PASS"
            if len(
                invalid_likert_values
            ) == 0
            else "FAIL"
        ),

        (
            "PASS"
            if len(
                invalid_constructs
            ) == 0
            else "FAIL"
        ),

        (
            "PASS"
            if np.isclose(
                manual_psycap_average,
                stored_psycap_average
            )
            else "FAIL"
        )
    ]
})

preprocessing_validation

                  Validation_Check Status
0                 Required columns   PASS
1            Duplicate Response_ID   PASS
2             Exact duplicate rows   PASS
3          Missing required values   PASS
4               Likert value range   PASS
5            Construct value range   PASS
6  PsyCap calculation verification   PASS

Save Validation Summary

In [80]:
VALIDATION_REPORT_PATH = (
    REPORT_DIR
    / "Preprocessing_Validation_Summary.csv"
)

preprocessing_validation.to_csv(
    VALIDATION_REPORT_PATH,
    index=False
)

print(
    "Preprocessing validation saved:",
    VALIDATION_REPORT_PATH
)

Preprocessing validation saved: d:\internship-employability-project\reports\phase3\preprocessing\Preprocessing_Validation_Summary.csv

In [81]:
print(
    "PHASE 03 — STEP 01 COMPLETE"
)

print(
    "\nRows:",
    len(df)
)

print(
    "PsyCap items:",
    len(
        PSYCAP_ITEMS
    )
)

print(
    "EVS items:",
    len(
        EVS_ITEMS
    )
)

print(
    "PsyCap constructs:",
    list(
        PSYCAP_CONSTRUCTS.keys()
    )
)

print(
    "Target:",
    "EVS_avg"
)

print(
    "\nPrepared dataset:",
    PREPARED_DATA_PATH
)

PHASE 03 — STEP 01 COMPLETE

Rows: 1000
PsyCap items: 12
EVS items: 12
PsyCap constructs: ['Hope_avg', 'Optimism_avg', 'Resilience_avg', 'SelfEfficacy_avg']
Target: EVS_avg

Prepared dataset: d:\internship-employability-project\data\processed\phase3_psycap_prepared.csv

## Step 01 Conclusion

The Phase 03 Psychological Capital → Employability dataset was successfully prepared for further statistical and machine-learning analysis.

The preprocessing stage validated the required questionnaire columns, checked duplicate responses and missing values, and confirmed that the Psychological Capital and Employability item responses were within the valid 1–5 Likert range.

Four Psychological Capital construct scores were created:

- Hope
- Optimism
- Resilience
- Self-Efficacy

An overall Psychological Capital score was also calculated.

The existing Employability structure was preserved, and an overall Employability score (`EVS_avg`) was created as the prediction target.

Separate item-level, construct-level, and overall Psychological Capital feature datasets were saved to support objective feature-representation comparison in later machine-learning stages.

The prepared dataset is now ready for Step 02 — Reliability Analysis.

In [82]:
PSYCAP_ITEM_LABELS = {
    "PsyCap1": "I can find various ways to overcome obstacles that arise during my studies.",
    "PsyCap2": "I realize that different approaches can be used to overcome the problems I face in my studies.",
    "PsyCap3": "I am committed to doing my best and working hard to achieve the goals I set.",

    "PsyCap4": "I have high hopes that I can succeed in my learning activities.",
    "PsyCap5": "I am optimistic that the time and effort I invest now will bring positive results in the future.",
    "PsyCap6": "I tend to identify positive lessons from my learning experiences, whether they involve success or failure.",

    "PsyCap7": "I can identify and analyze problems that arise during my learning activities.",
    "PsyCap8": "When I receive low grades, I try to identify the reasons and find ways to improve.",
    "PsyCap9": "I understand that failure can happen, and I am able to recover and continue working toward long-term success.",

    "PsyCap10": "I believe that I can successfully complete difficult tasks.",
    "PsyCap11": "I am confident enough to ask my teacher or lecturer for help when I have difficulty completing an assignment.",
    "PsyCap12": "I am confident that I can make a meaningful and useful contribution to others using my abilities."
}

In [83]:
codebook_rows = []

for construct, items in PSYCAP_CONSTRUCTS.items():

    for item in items:

        codebook_rows.append({
            "Item_Code": item,
            "Construct": construct.replace("_avg", ""),
            "Question": PSYCAP_ITEM_LABELS[item]
        })

psycap_codebook = pd.DataFrame(
    codebook_rows
)

psycap_codebook

   Item_Code     Construct                                           Question
0    PsyCap1          Hope  I can find various ways to overcome obstacles ...
1    PsyCap2          Hope  I realize that different approaches can be use...
2    PsyCap3          Hope  I am committed to doing my best and working ha...
3    PsyCap4      Optimism  I have high hopes that I can succeed in my lea...
4    PsyCap5      Optimism  I am optimistic that the time and effort I inv...
5    PsyCap6      Optimism  I tend to identify positive lessons from my le...
6    PsyCap7    Resilience  I can identify and analyze problems that arise...
7    PsyCap8    Resilience  When I receive low grades, I try to identify t...
8    PsyCap9    Resilience  I understand that failure can happen, and I am...
9   PsyCap10  SelfEfficacy  I believe that I can successfully complete dif...
10  PsyCap11  SelfEfficacy  I am confident enough to ask my teacher or lec...
11  PsyCap12  SelfEfficacy  I am confident that I can make a meaningful an...

In [84]:
psycap_codebook.to_csv(
    REPORT_DIR / "PsyCap_Questionnaire_Codebook.csv",
    index=False
)

In [85]:
if "data_source" in df.columns:

    data_source_summary = (
        df["data_source"]
        .value_counts(
            dropna=False
        )
        .rename_axis("Data_Source")
        .reset_index(
            name="Count"
        )
    )

    data_source_summary[
        "Percentage"
    ] = (
        data_source_summary["Count"]
        / len(df)
        * 100
    )

    data_source_summary

In [86]:
data_source_summary.to_csv(
    REPORT_DIR / "Data_Source_Summary.csv",
    index=False
)